# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#

SITE_NAME: 
HOST_NAME: http://localhost:3000
#asset host for template
ASSETS_HOST: http://localhost:3003

#send email
GMAIL_USERNAME: 
GMAIL_PASSWORD: sdf.com

QMAIL_USERNAME: sdf@qq.com
QMAIL_PASSWORD: sdf.com

MAILGUN_USERNAME: sdf@yufuwu.cn
MAILGUN_PASSWORD: fdsf

#Use on email
DOMAIN_NAME: localhost

#Admin
ADMIN_NAME: sdf
ADMIN_EMAIL: sdf@inruby.com
ADMIN_PASSWORD: sdf
ROLES: [admin, user, VIP]

#send sms
ADMIN_PHONE: 18080810818|18280673990


#send sms
SMS_BAO_USER: sdf
SMS_BAO_PASSWORD: sdf
SMS_MAX_CHARACTER_COUNT: 64

#Qiniu store
QINIU_ACCESS_KEY: sdfsdfdsf
QINIU_SECRET_KEY: ss-M4m-NLSaP0-OTGD2_eCCsqId_

#
#Alipay
ALIPAY_PID: ssfefefe
ALIPAY_KEY: 2pyzptdb47wo13fxdhsy9dfewfwfe0wie
ALIPAY_SELLER_EMAIL: kenrfwef@.com

#payment
PRICE_BASE: 60
PRICE_VIP: 180
PRICE_BIZ: 2000